### ISSUE TITLE
Compilation instruction

### ISSUE THREAD

**Issue by nmss** [jaxnX/DmgMeter#1]
Hello,

it would be nice to have some compilation instruction to be able to easily build the program :)

**Comment by cnelsonsic** [comment]
Try opening https://github.com/jaxnX/DmgMeter/blob/GW2/jaxnX/jaxnX.pro in QtCreator.

**Comment by pigoz** [comment]
It compiled fine on OSX with the usual (for Qt projects):

```
qmake
make
```

But on OSX there is no Fullscreen Windowed mode cause the wine version that ArenaNet uses is outdated and sucks. Maybe I'll provide patches later so it works in windowed mode.

**Comment by nmss** [comment]
Thanks it worked well with QtCreator :+1: 
(Windows 7 user here)
